name: CD - Deploy to Minikube

on:
  push:
    branches:
      - main
    paths:
      - "k8s/**"
      - "monitor/**"
      - ".github/workflows/cd.yml"

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install Minikube
        run: |
          curl -LO https://storage.googleapis.com/minikube/releases/latest/minikube-linux-amd64
          sudo install minikube-linux-amd64 /usr/local/bin/minikube

      - name: Start Minikube inside GitHub Actions
        run: |
          minikube start --driver=docker
          kubectl cluster-info

      - name: Pull latest image from Docker Hub into Minikube
        run: |
          minikube image pull ${{ secrets.DOCKERHUB_USERNAME }}/monitor:latest

      - name: Apply Kubernetes manifests
        run: |
          kubectl apply -f k8s/
          kubectl get all

      - name: Restart deployment
        run: |
          kubectl rollout restart deployment/monitor
          kubectl rollout status deployment/monitor
