name: CI - Build and Push to Docker Hub

on:
  push:
    branches:
      - main
  workflow_dispatch:  # permite rodar manualmente

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
      # 1️⃣ Checkout do código
      - name: Checkout code
        uses: actions/checkout@v4

      # 2️⃣ Login no Docker Hub usando os secrets
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      # 3️⃣ Build da imagem Docker
      - name: Build Docker image
        run: |
          docker build -t luizcolli/monitor:latest -f monitor/Dockerfile .

      # 4️⃣ Push da imagem para o Docker Hub
      - name: Push Docker image to Docker Hub
        run: |
          docker push luizcolli/monitor:latest
